@startuml

class std::runtime_exception

class ChorbRoundDanceException extends std::runtime_exception

class InvalidDirectionException extends ChorbRoundDanceException

class InvalidCommandException extends ChorbRoundDanceException

class NonExistingDancerException extends ChorbRoundDanceException

@enduml
